// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLijN9U1vqxozi37To5Ew8t2tMKJQ4Q_c',
    appId: '1:122114115247:web:b07450fb18b9846c3cb65a',
    messagingSenderId: '122114115247',
    projectId: 'ecommerce-app-68668',
    authDomain: 'ecommerce-app-68668.firebaseapp.com',
    storageBucket: 'ecommerce-app-68668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP8ynP2Dxssk9YU444MSDZWCHJxPvFqek',
    appId: '1:122114115247:android:e5bf2f613dfee05f3cb65a',
    messagingSenderId: '122114115247',
    projectId: 'ecommerce-app-68668',
    storageBucket: 'ecommerce-app-68668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtB1VN6yZ3kYGBP42ZQLfj_oMreUAz93o',
    appId: '1:122114115247:ios:5adff26c4959ddae3cb65a',
    messagingSenderId: '122114115247',
    projectId: 'ecommerce-app-68668',
    storageBucket: 'ecommerce-app-68668.firebasestorage.app',
    iosBundleId: 'com.ecommerce.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtB1VN6yZ3kYGBP42ZQLfj_oMreUAz93o',
    appId: '1:122114115247:ios:5adff26c4959ddae3cb65a',
    messagingSenderId: '122114115247',
    projectId: 'ecommerce-app-68668',
    storageBucket: 'ecommerce-app-68668.firebasestorage.app',
    iosBundleId: 'com.ecommerce.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLijN9U1vqxozi37To5Ew8t2tMKJQ4Q_c',
    appId: '1:122114115247:web:1e2960bd84c113fd3cb65a',
    messagingSenderId: '122114115247',
    projectId: 'ecommerce-app-68668',
    authDomain: 'ecommerce-app-68668.firebaseapp.com',
    storageBucket: 'ecommerce-app-68668.firebasestorage.app',
  );
}
